### ISSUE TITLE
Error compiling ndt7-client on Windows

### ISSUE THREAD

**Issue by pvouzis** [m-lab/ndt7-client-go#50]
When I try to build ndt7-client on windows I get

C:\Users\panos\ndt7-client-go>go get ./cmd/ndt7-client
# github.com/m-lab/tcp-info/inetdiag
..\go\pkg\mod\github.com\m-lab\tcp-info@v1.3.0\inetdiag\inetdiag.go:88:2: undefined: unix.AF_INET

Is there something different I need to do to compile it on Windows?

Thanks,
Panos

**Comment by marioja** [comment]
I have the same problem.  Is there an update on this issue?

**Comment by critzo** [comment]
@bassosimone @stephen-soltesz I believe this client is not supported in Windows. Could you please confirm?

**Comment by bassosimone** [comment]
There are some dependencies that do not work under Linux. To make this client work under Linux, there is need to write shims for all the functionality used under Linux so that the code compiles.

**Comment by critzo** [comment]
@bassosimone did you mean Windows instead of Linux in the previous comment?

**Comment by bassosimone** [comment]
yes, sorry!

**Comment by critzo** [comment]
Thanks @bassosimone . If you or others have a list of the dependencies that we could add in an issue here, perhaps others can look into meeting them under Windows.

**Comment by bassosimone** [comment]
No, I don't have a list. I think anyone that wants to work on this problem needs to `go get ./cmd/ndt7-client` from Windows (or cross compile it for Windows from other OSes), see what breaks, and iteratively fix it.

**Comment by marioja** [comment]
I know what a shim is but I don't understand how it applies here.  There is already a windows ndt7-client.exe so I would assume that all required "shims" would already be committed.  The error initially reported is related to UNIX domain sockets, so I do not think the code without change can work on windows.

**Comment by critzo** [comment]
@marioja M-Lab does not maintain or support a Windows executable for ndt7-client-go. If someone else is maintaining one, we'd like to know about it, but we can't vouch for it, especially given #47

I would guess that the "shims" referenced by @bassosimone are about building in support for whatever the windows alternative to UNIX domain sockets is.

**Comment by bassosimone** [comment]
I may have used the wrong term, maybe. So, when I compile for Windows I see:

```
% GOOS=windows GOARCH=amd64 go build -v ./cmd/ndt7-client
[...]
.../go/pkg/mod/github.com/m-lab/tcp-info@v1.3.0/inetdiag/inetdiag.go:88:2: undefined: unix.AF_INET
```

So, m-lab/tcp-info is only used by `internal/download/download_test.go` _but_ `spec/spec.go` imports `github.com/m-lab/ndt-server/ndt7/model`, which in turn imports from `m-lab/tcp-info`. This repository does not contain code that compiles when you're not using Linux. I see two possible solutions here:

1. vendor all the required data structures so `spec/spec.go` does not depend on `m-lab/ndt-server`

2.1. make `m-lab/tcp-info` compile also with any non-Linux system

2.2. guarantee with tests that the build does not break in the future on any system

2.3. make sure a significant subset of `m-lab/ndt-server` compiles also with non-Linux systems

2.4. guarantee with tests that it does not break in the future

The "guarantee with tests" aspect is really important here because `m-lab/tcp-info` and `m-lab/ndt-server` are two repositories mainly meant to work on Linux systems, so it's possible a future commit could break the Go client again.

Hope this explanation is better and more explicit than my previous reference to a "shim". And, as I said, maybe I used the wrong word here; what could be a better word to the describe all the above?

**Comment by stephen-soltesz** [comment]
It looks like the only dependency is on the constant [`unix.AF_INET`][1] which on linux systems has had a value of 2 since before Linux v1.0. The inetdiag.go file already hard codes AF_INET6 to support Darwin, I think it would be defensible to change AF_INET to a local constant to allow cross platform compilations for Windows also.

[1]: https://github.com/m-lab/tcp-info/blob/c5977c894b1521ce1b8bb7b299293fabc1f8c398/inetdiag/inetdiag.go#L88

**Comment by stephen-soltesz** [comment]
Updated the tcpinfo change in go.mod -- https://github.com/m-lab/ndt7-client-go/pull/53

Please let me know if this does not resolve the ndt7-client build for windows.
